### ISSUE TITLE
How do type check constructors?

### ISSUE THREAD

**Issue by kindlychung** [zatonovo/lambda.r#22]
For example, this would be legit, but nonsensical:

    PointCartesian(x, y) %as% list(x = x, y = y)
    PointCartesian("a", "b")

How do you make sure that both x and y are numerics?

**Comment by muxspace** [comment]
Hi this works the same as with type constraints on normal functions:
```
> PointCartesian(x,y) %::% numeric:numeric:list
> PointCartesian(x, y) %as% list(x = x, y = y)
>
> z <- PointCartesian(1,3)
>
> PointCartesian('a','b')
Error in UseFunction(type.fn, type.name, ...) :
  No valid function for 'PointCartesian(a,b)'
```

**Comment by kindlychung** [comment]
That's what I tried, but I got this on R 3.1.3:

    >     PointCartesian(x, y) %::% numeric : numeric : list
    >     PointCartesian(x, y) %as% list(x = x, y = y)
    >     PointCartesian(1, 2)
    Error in UseFunction(type.fn, type.name, ...) :
      Expected 'PointCartesian' as return type but found 'list' for 'PointCartesian(1,2)'

**Comment by muxspace** [comment]
What version of lambda.r are you using?

**Comment by kindlychung** [comment]
1.1.7

**Comment by kindlychung** [comment]
I installed by install.package("lambda.r"), so it's from CRAN. Should I install from github instead?

**Comment by muxspace** [comment]
Should be the same. I'm on R3.1.2. LMC on R3.1.3.

**Comment by muxspace** [comment]
Hi, I don't have a VM handy where I can install R3.1.3. Can you try this and let me know if it works in the interim:

```
rm(PointCartesian)
PointCartesian(x,y) %::% numeric : numeric : .
PointCartesian(1, 2)
```

The . is a special type variable that says "I don't care about the type".

**Comment by kindlychung** [comment]
I restarted R and did the same thing again, and it worked.

I probably define something different earlier, like

    PointCartesian(x, y) %::% numeric : numeric : PointCartesian

But normally this should have been overwritten later, right?

**Comment by kindlychung** [comment]
Oh, and I also have tried the "i don't care" type before, same error. But now it all works, both `list` and `.`.

**Comment by muxspace** [comment]
The type constraints don't get overwritten, as there is no way to know which ones are valid. In some situations, both could be legal. e.g.

```
library(lambda.r)
library(futile.logger)

do_something(date) %::% character : a
do_something(date) %as% do_something(as.Date(date))

do_something(date) %::% Date : a
do_something(date) %as% flog.info("I did something for %s", date)

do_something('2015-02-11')
```

If you print the function, you'll see all the definitions bound to the function name.
```
> do_something
<function>
[[1]]
do_something(date) %::% character:a
do_something(date) %as% ...
[[2]]
do_something(date) %::% Date:a
do_something(date) %as% ...
```

**Comment by kindlychung** [comment]
I see, that's function overloading.
