### ISSUE TITLE
Nested %as% does not work

### ISSUE THREAD

**Issue by kindlychung** [zatonovo/lambda.r#25]
Here is an example:

    require(lambda.r)
    Function(x) %when% { is.function(x) } %as% x
    addn.factory(n) %::% numeric : Function
    addn.factory(n) %as% {
        addn(x) %as% {
            x + n
        }
        Function(addn)
    }

    Error in get_name(it) :
      Function must start with a symbol (instead of '(')

**Comment by muxspace** [comment]
This is a known unsupported feature.
