### ISSUE TITLE
More specific error messages in guards

### ISSUE THREAD

**Issue by kindlychung** [zatonovo/lambda.r#27]
For example:

    OddNumber(x) %::% integer : .
    OddNumber(x) %when% {
        (x %% 2) == 1
    } %as% {
        x
    }

Feed it an even number and it will complain:

    > OddNumber(2L)
    Error in UseFunction(type.fn, type.name, ...) :
      No valid function for 'OddNumber(2)'

But it doesn't say what exactly went wrong. How about something like this:

    OddNumber(x) %::% integer : .
    OddNumber(x) %when% {
        if(x %% 2 == 1) TRUE else {
            warning("OddNumber: must feed me an ODD number!")
            FALSE
        }
    } %as% {
        x
    }

But this currently won't work:

    Error in parse_guard(it) : Invalid symbol '{'in function definition

**Comment by kindlychung** [comment]
It may be simplified further: 

    require(lambda.r)
    OddNumber(x) %::% integer : .
    OddNumber(x) %when% {
        x %% 2 == 1 %||% "You must give me an odd number!"
    } %as% {
        x
    }

**Comment by muxspace** [comment]
I like your thinking on this, but the reason I did it this way is to handle multiple function clauses. Your approach assumes a single clause. If you had multiple clauses, which error message would you print? I'm open to alternative implementations, but a core requirement is to handle multiple function clauses and pattern matching.

**Comment by muxspace** [comment]
Hi, do you have any other thoughts on this? If not, I'm going to close it. Cheers, Brian

**Comment by kindlychung** [comment]
Yeah, please close it.
