### ISSUE TITLE
README notes

### ISSUE THREAD

**Issue by AndrewHannigan** [zatonovo/lambda.r#34]
Just two thoughts on the README.md.  
1) I think it is worth explicitly mentioning that capitalizing a function name makes it a type constructor.
```
> Int(x) %as% x
> int(x) %as% x
> Int(1)
[1] 1
attr(,"class")
[1] "Int"     "numeric"
> int(1)
[1] 1
```

2) There is a line in the Auto Replace and Sealing Definitions that is confusing:

> For example take this simple reciprocal function. It has two three clauses and two type constraints. There is an explicit bug in the body of the second variant. Note that the signatures for variants 2 and 3 are identical and the only thing that distinguishes them are ther type constraints.

Note "two three clauses".  Also it would be useful to define the term "clause".  I believe you are referring to a block of function variants associated with a single type constraint, but that is only my best guess based on context.  Also I would suggest specifically saying "the body of the second variant of the first clause".    Lastly, ther -> their.  

Sorry to be a stickler - I comment because I care!  Great work on the package.

**Comment by muxspace** [comment]
Thanks for the comments. Do you want to submit a pull request with the changes you recommend?

**Comment by AndrewHannigan** [comment]
Yup sure thing






On Wed, Dec 21, 2016 at 2:20 PM -0500, "Brian Lee Yung Rowe" <notifications@github.com> wrote:












Thanks for the comments. Do you want to submit a pull request with the changes you recommend?
